name: 'Install packages'
description: 'Install required packages for building the project'

runs:
  using: "composite"
  steps:
    # -------------------------
    # ðŸ§ Linux Dependencies
    # -------------------------
    - name: Install Linux Dependencies (SFML2 + audio, Ninja, Valgrind)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -eux
        sudo apt-get update -y
        # SFML 2.x with audio + common GL/X11 deps + Ninja + Valgrind
        sudo apt-get install -y --no-install-recommends \
          libsfml-dev \
          libopenal-dev \
          libsndfile1-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libdrm-dev \
          libgbm-dev \
          libfreetype6-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxi-dev \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0 \
          ninja-build \
          valgrind

        # Help CMake resolve the correct SFML 2 config path
        echo "SFML_DIR=/usr/lib/x86_64-linux-gnu/cmake/SFML" >> "$GITHUB_ENV"

        # Quick probe to fail early if audio component is missing
        cat > _probe_sfml.cmake <<'CMK'
        cmake_minimum_required(VERSION 3.18)
        # NOTE: components must be lowercase in SFML 2.x
        find_package(SFML 2 REQUIRED COMPONENTS system window graphics audio)
        message(STATUS "SFML2 FOUND: ${SFML_FOUND} ; INCLUDE=${SFML_INCLUDE_DIRS}")
        CMK
        cmake -P _probe_sfml.cmake

    # -------------------------
    # ðŸ macOS Dependencies
    # -------------------------
    - name: Install macOS Dependencies
      shell: bash
      if: runner.os == 'macOS'
      run: |
        set -eux
        brew update
        brew install sfml ninja || true
        # Expose SFML_DIR so CMake finds the config files reliably
        SFML_PREFIX="$(brew --prefix sfml 2>/dev/null || true)"
        if [[ -n "${SFML_PREFIX}" && -d "${SFML_PREFIX}/lib/cmake/SFML" ]]; then
          echo "SFML_DIR=${SFML_PREFIX}/lib/cmake/SFML" >> "$GITHUB_ENV"
        fi

    # -------------------------
    # ðŸªŸ Windows Dependencies
    # -------------------------
    - name: Install Windows Dependencies (Ninja)
      shell: bash
      if: runner.os == 'Windows'
      run: |
        choco install -y ninja

    - name: Cache vcpkg
      if: runner.os == 'Windows'
      uses: actions/cache@v4
      id: cache-vcpkg
      with:
        path: |
          vcpkg
          ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: vcpkg-cache-${{ runner.os }}-${{ matrix.cxx }}

    - name: Install Windows Dependencies (vcpkg)
      shell: bash
      if: runner.os == 'Windows' && matrix.cxx == 'cl'
      run: |
        set -eux
        if [[ ! -d "vcpkg" || "${{ steps.cache-vcpkg.outputs.cache-hit }}" != "true" ]]; then
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat
        else
          echo "vcpkg cache restored."
        fi
        ./vcpkg/vcpkg install sfml:x64-windows
        echo "VCPKG_TOOLCHAIN_FILE=${GITHUB_WORKSPACE}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> "$GITHUB_ENV"
