name: 'Install packages'
description: 'Install required packages for building the project'

runs:
  using: "composite"
  steps:
    # -------------------------
    # ðŸ§ Linux Dependencies
    # -------------------------
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      uses: ./.github/actions/install-linux-deps

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends valgrind

    # -------------------------
    # ðŸ macOS Dependencies
    # -------------------------
    - name: Install macOS Dependencies
      shell: bash
      if: runner.os == 'macOS'
      run: |
        set -eux
        brew update
        brew install sfml ninja

    # -------------------------
    # ðŸªŸ Windows Dependencies
    # -------------------------
    
    # --- THIS IS THE FIX ---
    - name: Install Windows Dependencies (Ninja and SFML deps)
      shell: bash
      if: runner.os == 'Windows'
      run: |
        # Install ninja
        choco install ninja
        
        # Install SFML's dependencies (Freetype, OpenAL, Vorbis, Ogg)
        # This is required for SFMLConfig.cmake to pass its internal checks
        choco install freetype openal-soft libvorbis libogg
        
    - name: Install Windows Dependencies (Download SFML)
      shell: bash
      if: runner.os == 'Windows' && matrix.cxx == 'cl'
      run: |
        set -eux
        # Download SFML for Visual Studio 2022 (vc17), 64-bit
        curl -L https://www.sfml-dev.org/files/SFML-2.6.1-windows-vc17-64-bit.zip -o sfml.zip
        
        # Unzip to a folder named "sfml_install"
        7z x sfml.zip -osfml_install
        
        # Set an env var pointing to the unzipped folder
        echo "SFML_DIR_WINDOWS=${GITHUB_WORKSPACE}/sfml_install/SFML-2.6.1" >> $GITHUB_ENV
