name: 'Install packages'
description: 'Install required packages for building the project'

runs:
  using: "composite"
  steps:
    # -------------------------
    # 🐧 Linux Dependencies
    # -------------------------
    - name: Install Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        set -eux  # stop on errors and print commands
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends software-properties-common
        sudo add-apt-repository -y universe
        sudo apt-get update -y

        # Install SFML (compatible with Ubuntu 22.04 and 24.04)
        if apt-cache show libsfml-dev >/dev/null 2>&1; then
          echo "Installing unified SFML package (libsfml-dev)"
          sudo apt-get install -y --no-install-recommends ninja-build libsfml-dev
        else
          echo "Installing legacy SFML split packages"
          sudo apt-get install -y --no-install-recommends ninja-build \
            libsfml-audio-dev \
            libsfml-graphics-dev \
            libsfml-network-dev \
            libsfml-system-dev \
            libsfml-window-dev
        fi

        # Workaround for LLVM bug on some runners
        sudo sysctl vm.mmap_rnd_bits=28 || true

    # -------------------------
    # 🍏 macOS Dependencies
    # -------------------------
    - name: Install macOS Dependencies
      shell: bash
      if: runner.os == 'macOS'
      run: |
        set -eux
        brew update
        brew install sfml ninja

    # -------------------------
    # 🪟 Windows Dependencies
    # -------------------------
    - name: Install Windows Dependencies
      shell: bash
      if: runner.os == 'Windows'
      run: |
        choco install sfml ninja

    # -------------------------
    # 🧰 Optional: Clang (for MSAN builds)
    # -------------------------
    - name: Install Clang ${{ matrix.clang_ver }}
      if: runner.os == 'Linux' && matrix.runs_msan == true
      uses: nick-fields/retry@v3
      with:
        shell: bash
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh ${{ matrix.clang_ver }}

    - name: Install libc++ (Linux Clang ${{ matrix.clang_ver }})
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_msan == true
      run: |
        sudo apt-get install -y --no-install-recommends \
          libc++-${{ matrix.clang_ver }}-dev libc++abi-${{ matrix.clang_ver }}-dev

    # -------------------------
    # 🧪 Optional: Valgrind for memory checking
    # -------------------------
    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        sudo apt-get install -y --no-install-recommends valgrind
