name: 'Configure CMake'
description: 'Common logic for CMake configuration'
inputs:
  warnings_as_errors:
    description: 'Treat warnings as errors'
    required: false
    default: 'OFF'
  custom_flags:
    description: 'Custom CMake configuration flags'
    required: false

runs:
  using: "composite"
  steps:
    # Cache third-party deps pulled into the build tree (optional)
    - name: Cache deps
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          ${{ env.BUILD_DIR }}/_deps
        key: cache-${{ matrix.cmake_generator }}-${{ matrix.os }}-${{ matrix.cxx }}-${{ matrix.asan_name }}-${{ env.BUILD_TYPE }}-${{ env.SFML_VERSION }}

    - name: Cache Ninja deps
      uses: actions/cache@v4
      if: matrix.cmake_generator == 'Ninja'
      id: cache-deps-ninja
      with:
        path: |
          ${{ env.BUILD_DIR }}/.ninja_deps
          ${{ env.BUILD_DIR }}/.ninja_log
        key: ${{ matrix.os }}-${{ matrix.cxx }}-${{ matrix.asan_name }}-ninja-cache-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: ${{ matrix.os }}-${{ matrix.cxx }}-${{ matrix.asan_name }}-ninja-cache-

    # ---- Windows: MinGW toolchain path (for matrix.cxx == g++) ----
    - name: Cache MinGW
      uses: actions/cache@v4
      id: cache-mingw
      if: runner.os == 'Windows' && matrix.cxx == 'g++'
      with:
        path: gcc
        key: ${{ runner.os }}-${{ env.MINGW_VER }}

    - name: Download toolchain (MinGW)
      uses: suisei-cn/actions-download-file@v1.6.0
      id: download-mingw-gcc
      if: runner.os == 'Windows' && matrix.cxx == 'g++' && steps.cache-mingw.outputs.cache-hit != 'true'
      with:
        url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/${{ env.MINGW_VER }}"
        target: compiler/

    - name: Install toolchain (MinGW)
      shell: bash
      if: runner.os == 'Windows' && matrix.cxx == 'g++' && steps.cache-mingw.outputs.cache-hit != 'true'
      run: |
        7z x "compiler/${{ steps.download-mingw-gcc.outputs.filename }}" -ogcc

    # ---- Windows: MSVC environment (for matrix.cxx == cl) ----
    - name: Setup MSVC dev cmd
      if: runner.os == 'Windows' && matrix.cxx == 'cl'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Select MSVC compiler (set CC/CXX)
      if: runner.os == 'Windows' && matrix.cxx == 'cl'
      shell: bash
      run: |
        set -euo pipefail
        echo "CC=cl"  >> "$GITHUB_ENV"
        echo "CXX=cl" >> "$GITHUB_ENV"

    # ---- Configure (Windows MinGW) ----
    - name: Configure CMake (MinGW)
      shell: bash
      if: runner.os == 'Windows' && matrix.cxx == 'g++'
      run: |
        set -euo pipefail
        PATH="$(pwd)/gcc/mingw64/bin:${PATH}"
        GEN="${{ matrix.cmake_generator }}"
        if [ -z "${GEN}" ]; then GEN="Ninja"; fi
        bash ./scripts/cmake.sh configure \
          -s "${GITHUB_WORKSPACE}" \
          -b "${{ env.BUILD_DIR }}" \
          -g "${GEN}" \
          -c "${{ env.BUILD_TYPE }}" \
          -i "${GITHUB_WORKSPACE}/artifacts" \
          -e "-DPROJECT_WARNINGS_AS_ERRORS=${{ inputs.warnings_as_errors }} -DGITHUB_ACTIONS=${GITHUB_ACTIONS} ${{ inputs.custom_flags }}"

    # ---- Configure (everything else, incl. Windows MSVC) ----
    - name: Configure CMake
      shell: bash
      if: ${{ !(runner.os == 'Windows' && matrix.cxx == 'g++') }}
      run: |
        set -euo pipefail
        GEN="${{ matrix.cmake_generator }}"
        if [ -z "${GEN}" ]; then GEN="Ninja"; fi
        bash ./scripts/cmake.sh configure \
          -s "${GITHUB_WORKSPACE}" \
          -b "${{ env.BUILD_DIR }}" \
          -g "${GEN}" \
          -c "${{ env.BUILD_TYPE }}" \
          -i "${GITHUB_WORKSPACE}/artifacts" \
          -e "-DPROJECT_WARNINGS_AS_ERRORS=${{ inputs.warnings_as_errors }} -DGITHUB_ACTIONS=${GITHUB_ACTIONS} ${{ inputs.custom_flags }}"
