name: 'Configure CMake'
description: 'Common logic for CMake configuration'
inputs:
  warnings_as_errors:
    description: 'Treat warnings as errors'
    required: false
    default: 'OFF'
  custom_flags:
    description: 'Custom CMake configuration flags'
    required: false
  cache_key:
    description: 'Deps cache key'
    required: false
    default: 'cache-deps'

runs:
  using: "composite"
  steps:
    # ... (all the cache steps and MinGW steps at the beginning are fine) ...
    
    - name: Cache Ninja deps
      uses: actions/cache@v4.2.4
      # ... (omitted for brevity) ...

    - name: Cache MinGW
      uses: actions/cache@v4.2.4
      # ... (omitted for brevity) ...

    - name: Download toolchain (MinGW)
      uses: suisei-cn/actions-download-file@v1.6.0
      # ... (omitted for brevity) ...

    - name: Install toolchain (MinGW)
      shell: bash
      # ... (omitted for brevity) ...

    - name: Configure CMake (MinGW)
      shell: bash
      if: runner.os == 'Windows' && matrix.cxx == 'g++'
      # ... (omitted for brevity) ...

    # --- THIS IS THE FIX ---
    # This is the step for all non-MinGW builds (including Windows MSVC)
    - name: Configure CMake
      shell: bash
      if: ${{ !(runner.os == 'Windows' && matrix.cxx == 'g++') }}
      run: |
        export CMAKE_GENERATOR=${{ matrix.cmake_generator }}

        # Define extra flags based on OS
        EXTRA_CMAKE_FLAGS="${{ inputs.custom_flags }}"
        if [[ "${{ runner.os }}" == "Windows" && "${{ matrix.cxx }}" == "cl" ]]; then
          echo "Adding SFML path for Windows MSVC: ${{ env.SFML_DIR_WINDOWS }}"
          # We pass the path to CMAKE_PREFIX_PATH so find_package() can find SFML
          EXTRA_CMAKE_FLAGS+=" -DCMAKE_PREFIX_PATH=${{ env.SFML_DIR_WINDOWS }}"
        fi
        
        bash ./scripts/cmake.sh configure \
          -b ${{ env.BUILD_DIR }} \
          -c ${{ env.BUILD_TYPE }} \
          -e "-DPROJECT_WARNINGS_AS_ERRORS=${{ inputs.warnings_as_errors }} -DGITHUB_ACTIONS=${GITHUB_ACTIONS} ${EXTRA_CMAKE_FLAGS}" \
          -i ${GITHUB_WORKSPACE}/artifacts \
          -s ${GITHUB_WORKSPACE}
