name: 'Install common Linux dependencies'
description: 'Common logic for Linux dependencies installation'
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        # 1. Instalează pachetul necesar pentru a adăuga depozite
        sudo apt-get install -y --no-install-recommends software-properties-common
        
        # 2. Adaugă depozitul 'universe'
        sudo add-apt-repository universe
        
        # 3. Rulează update DIN NOU pentru a încărca lista de pachete din 'universe'
        sudo apt-get update
        
        # 4. Acum instalează pachetele
        sudo apt-get install -y --no-install-recommends \
          libsfml-system-dev \
          libsfml-window-dev \
          libsfml-graphics-dev \
          libsfml-audio-dev \
          libxrandr-dev \
          libxcursor-dev \
          libudev-dev \
          libopenal-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libdrm-dev \
          libgbm-dev \
          libfreetype6-dev \
          libxi-dev \
          xorg
      shell: bash
