name: 'Install common Linux dependencies'
description: 'Install all required Linux dependencies for building and testing'

runs:
  using: "composite"
  steps:
    - name: Install All Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        set -eux
        sudo apt-get update -y
        # Needed for add-apt-repository
        sudo apt-get install -y --no-install-recommends software-properties-common
        sudo add-apt-repository -y universe
        sudo apt-get update -y

        # --- THIS IS THE FIX ---
        # Install SFML (unified or split)
        if apt-cache show libsfml-dev >/dev/null 2>&1; then
          echo "Installing SFML (libsfml-dev)"
          sudo apt-get install -y --no-install-recommends libsfml-dev
        else
          echo "Installing legacy SFML split packages"
          sudo apt-get install -y --no-install-recommends \
            libsfml-audio-dev \
            libsfml-graphics-dev \
            libsfml-network-dev \
            libsfml-system-dev \
            libsfml-window-dev
        fi
        
        # --- Install all other packages ---
        echo "Installing common build, X11, and test dependencies"
        sudo apt-get install -y --no-install-recommends \
          ninja-build \
          xdotool \
          openbox \
          xorg \
          libxrandr-dev \
          libxcursor-dev \
          libudev-dev \
          libopenal-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libdrm-dev \
          libgbm-dev \
          libfreetype6-dev \
          libxi-dev \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0

        # https://github.com/llvm/llvm-project/issues/78354
        sudo sysctl vm.mmap_rnd_bits=28 || true
