name: "Install Linux deps for SFML 3"
description: "Apt packages required to build SFML 3 via vcpkg on Ubuntu runners"

runs:
  using: "composite"
  steps:
    - name: Apt update & base toolchain
      shell: bash
      run: |
        set -eux
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          build-essential cmake ninja-build pkg-config \
          git curl ca-certificates zip unzip tar

    - name: Compilers used by matrix (gcc-12/g++-12)
      if: env.CC == 'gcc-12' || env.CXX == 'g++-12'
      shell: bash
      run: |
        set -eux
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          gcc-12 g++-12

    # ---- SFML 3 system requirements on Ubuntu (per vcpkg/port + CMake output) ----
    - name: X11 / OpenGL dev headers for SFML 3
      shell: bash
      run: |
        set -eux
        # From the error: libx11, libxi, libxrandr, libxcursor, libudev, opengl
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          libx11-dev libxi-dev libxrandr-dev libxcursor-dev libudev-dev libgl1-mesa-dev

        # Helpful extras some setups need (not strictly required but common):
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          libxrender-dev libxinerama-dev libdrm-dev
